version: "3.9"

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DB_PATH=/data/database.db
      - BUFFER_SIZE=100
    depends_on:
      - db

  db:
    image: alpine/sqlite:latest
    volumes:
      - db-data:/data

  tests:
    build:
      context: .
      target: test
    volumes:
      - ./:/app
    command: ["pytest", "tests/", "-v"]

volumes:
  db-data:
